services:
  db:
    image: postgres:15-alpine
    container_name: rinha-db
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

  api:
    build: .
    container_name: rinha-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Variáveis que a API deve usar para se ligar ao banco
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: 123
      DB_NAME: rinha
    deploy:
      resources:
        limits:
          cpus: '0.3' # Total de 0.5 somando com o DB
          memory: 128M # Total de 256M somando com o DB
